### PR TITLE
Sandboxing message content.

### PR DESCRIPTION
**Pull request by herpiko**

### CODE REVIEW

**Comment by mdamt** [comment]
:thumbsup:

**Comment by emhaye** [comment]
Issue #97 
- Cegah kirim surel selama unggahan lampiran berlangsung :+1: 
- Cegah simpan surel selama unggahan lampiran berlangsung :-1:

**Comment by emhaye** [comment]
Sudah sip pak :+1:

**Comment by herpiko** [comment]
Terima kasih

**Pull request merged**
